server:
  port: 8082

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
    client:
      client-id: resource-server
      client-secret: secret
      authorized-grant-type: password
